### DISCUSSION TITLE
Tore calibration and error margin depending on calibration value

### DISCUSSION THREAD

**Discussion by mathieucarbou** [OpenEVSE/open_evse#23] [Q&A] [answered]
Hello,

Default calibration for ampmeter coming with OpenEVSE box is `$SA 220 0`. Which is perfect for normal / high charge current.

But when using solat diver, lower charge current are completely of by 0.25A and I need to set `$SA 190 0` to calibrate.

Here is a comparison with a Shelly EM which was confirmed being accurate:

![image](https://user-images.githubusercontent.com/61346/236951149-f269845f-d030-47c1-8a5f-037237a407da.png)

is there a way to set a sort of factor so that 190 is used for lower current and then 220 ?

Right now, in Home Assistant I am using an automation that is setting the right calibration value depending if I am using AUTO mode with solar divert (which means low charge currents) or Manual mode (which mean high charge current)

```yaml
  - alias: "OpenEVSE: Bugfix Calibration"
    trigger:
      - platform: state
        entity_id:
          - select.openevse_charge_control
          - switch.openevse_solar_divert
    condition: []
    action:
      - if:
          - condition: state
            entity_id: switch.openevse_solar_divert
            state: "on"
          - condition: state
            entity_id: select.openevse_charge_control
            state: Auto
        then:
          - service: mqtt.publish
            data:
              topic: "openevse/rapi/in/$SA"
              payload: "190 0"
        else:
          - service: mqtt.publish
            data:
              topic: "openevse/rapi/in/$SA"
              payload: "220 0"
    mode: single
```
